---
Name: ProductQuestionMain
---
Product:
  extensions:
    - ProductQuestion_ProductDecorator

ProductPage_Controller:
  extensions:
    - ProductQuestion_ProductControllerDecorator

OrderItem:
  extensions:
    - ProductQuestion_OrderItemExtension

ProductQuestion:
  number_per_row: 1

---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - ProductQuestion_ProductVariationDecorator


